// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAahv2u2U6KlSb8sOdHxofBaSZCQPTPkEU',
    appId: '1:695179801525:web:c176fbbabdc14ca5af1ffc',
    messagingSenderId: '695179801525',
    projectId: 'todoapp-4c3fd',
    authDomain: 'todoapp-4c3fd.firebaseapp.com',
    storageBucket: 'todoapp-4c3fd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi-3XU0vgaTBbjDuzqucsIIDBh1KgmyA8',
    appId: '1:695179801525:android:e5ed4f613489da93af1ffc',
    messagingSenderId: '695179801525',
    projectId: 'todoapp-4c3fd',
    storageBucket: 'todoapp-4c3fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFcQfzmluPEviwi2XhFgGzkEyTJcCJ0Ag',
    appId: '1:695179801525:ios:f22bb5d32bb4c149af1ffc',
    messagingSenderId: '695179801525',
    projectId: 'todoapp-4c3fd',
    storageBucket: 'todoapp-4c3fd.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFcQfzmluPEviwi2XhFgGzkEyTJcCJ0Ag',
    appId: '1:695179801525:ios:f22bb5d32bb4c149af1ffc',
    messagingSenderId: '695179801525',
    projectId: 'todoapp-4c3fd',
    storageBucket: 'todoapp-4c3fd.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAahv2u2U6KlSb8sOdHxofBaSZCQPTPkEU',
    appId: '1:695179801525:web:5c583104de00c7f7af1ffc',
    messagingSenderId: '695179801525',
    projectId: 'todoapp-4c3fd',
    authDomain: 'todoapp-4c3fd.firebaseapp.com',
    storageBucket: 'todoapp-4c3fd.firebasestorage.app',
  );
}
